# Copyright (c) 2025 Davi Saranszky Mesquita. All rights reserved.
# See LICENSE for license information.

# Do not use 'workflow_dispatch'

name: Coverage

on:
  push:
    branches:
      - pre
## TODO Using the '.github/workflows/coverage.yml', create a workflow in '.github/workflows'
## to check if there is any scenario that the product owner needs to review regarding business rules.
