# Do not use 'workflow_dispatch'

name: Issue State Reason Monitor

on:
  issues:
    types: [closed]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  handle_null_reason:
    if: github.event.issue.state_reason == null
    runs-on: ubuntu-latest

    steps:
      - name: Process issue closure
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const issue = context.payload.issue;
            const issueNumber = issue.number;

            const searchQuery = `repo:${owner}/${repo} is:pr is:open "${issueNumber}" in:body`;
            const search = await github.rest.search.issuesAndPullRequests({ q: searchQuery });
            const candidatePr = (search.data.items || []).find(item => Boolean(item.pull_request));

            let mergeResult = null;
            if (candidatePr) {
              const prNumber = candidatePr.number;
              try {
                mergeResult = await github.rest.pulls.merge({
                  owner,
                  repo,
                  pull_number: prNumber,
                  merge_method: 'merge'
                });
                core.info(`Pull request #${prNumber} merged.`);
              } catch (error) {
                core.warning(`Falha ao aceitar PR #${prNumber}: ${error.message}`);
              }
            } else {
              core.info('Nenhum pull request aberto relacionado encontrado.');
            }

            const comments = await github.paginate(github.rest.issues.listComments, {
              owner,
              repo,
              issue_number: issueNumber,
              per_page: 100
            });

            const lines = [];
            lines.push(`# Documentar issue ${issueNumber}`);
            lines.push('');
            lines.push('## Corpo original');
            lines.push(issue.body ? issue.body : '_Sem descricao fornecida._');
            lines.push('');
            lines.push('## Comentarios');
            if (!comments.length) {
              lines.push('_Sem comentarios._');
            } else {
              comments.forEach(comment => {
                const author = comment.user?.login || 'desconhecido';
                const body = comment.body || '_Sem texto._';
                lines.push(`- @${author}: ${body}`);
              });
            }
            lines.push('');
            lines.push('## Acao');
            lines.push('Atualizar SPEC.md com os pontos tratados nesta issue.');

            const newIssue = await github.rest.issues.create({
              owner,
              repo,
              title: `Documentar issue #${issueNumber} em SPEC.md`,
              body: lines.join('\n'),
              labels: ['run']
            });

            const noteLines = [];
            if (mergeResult && mergeResult.data && mergeResult.data.sha && candidatePr) {
              noteLines.push(`PR relacionado foi aceito: #${candidatePr.number}`);
            }
            noteLines.push(`Issue de documentacao criada: #${newIssue.data.number}`);

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: issueNumber,
              body: noteLines.join('\n')
            });
