name: 🐛 Relatorio de Bug
description: Reporte um bug para ajudar a melhorar o projeto
title: '[BUG] '
labels: ['bug', 'triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Notice: You can write this issue in any language, our system will translate it.

        Obrigado por dedicar seu tempo para relatar este bug! 🙏

        Forneca o maximo de detalhes possivel para nos ajudar a entender e reproduzir o problema.

  - type: textarea
    id: description
    attributes:
      label: Descricao
      description: Descreva com clareza o bug encontrado
      placeholder: 'Quando tentei [acao], [comportamento inesperado] ocorreu em vez de [comportamento esperado]'
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Passos para Reproduzir
      description: Informe os passos exatos para reproduzir o bug
      placeholder: |
        1. Ir para [local]
        2. Clicar em [elemento]
        3. Inserir [dados]
        4. Observar [comportamento]
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamento Esperado
      description: O que deveria acontecer?
      placeholder: 'O sistema deveria...'
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportamento Atual
      description: O que acontece de fato?
      placeholder: 'Em vez disso, o sistema...'
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severidade
      description: Qual a gravidade deste bug?
      options:
        - '🟢 Baixa (problema cosmetico, ha alternativa)'
        - '🟡 Media (afeta funcionalidade, sem alternativa simples)'
        - '🔴 Alta (funcionalidade principal quebrada)'
        - '🔴🔴 Critica (sistema inutilizavel ou perda de dados)'
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Ambiente
      description: Forneca informacoes relevantes do sistema
      placeholder: |
        - SO: [ex., macOS 14.1, Windows 11, Ubuntu 23.10]
        - Navegador: [ex., Chrome 119, Firefox 121]
        - Node.js/Runtime: [versao]
        - Versao do Projeto: [versao]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs de Erro / Capturas de Tela
      description: Inclua mensagens de erro, rastros de pilha ou capturas de tela
      placeholder: 'Cole o erro aqui ou anexe capturas de tela'

  - type: textarea
    id: additional
    attributes:
      label: Contexto Adicional
      description: Ha algum outro contexto que possa ajudar?
      placeholder: 'Percebi que isto comecou a acontecer apos a versao X...'

  - type: checkboxes
    id: verification
    attributes:
      label: Verificacao
      description: Verifique antes de enviar
      options:
        - label: Eu busquei issues existentes e isto nao eh duplicado
          required: true
        - label: Consigo reproduzir este bug de forma consistente
          required: true
        - label: Forneci todas as informacoes relevantes
          required: true
