# Copyright (c) 2025 Davi Saranszky Mesquita. All rights reserved.
# See LICENSE for license information.

# Do not use 'workflow_dispatch'

name: Coverage

on:
  push:
    branches:
      - pre

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: pre
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Cursor CLI
        run: |
          curl https://cursor.com/install -fsS | bash
          export PATH="$HOME/.cursor/bin:$PATH"
          echo "$HOME/.cursor/bin" >> $GITHUB_PATH

      - name: Run Cursor Agent
        env:
          CURSOR_API_KEY: ${{ secrets.CURSOR_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          export PATH="$HOME/.cursor/bin:$PATH"
          git config --local user.email "suporte@ideias.casa"
          git config --local user.name "AI"
          cursor-agent -p --model auto --force --output-format text "You have full access to git, GitHub CLI, and PR operations. You can also run any command you want.
          Inside the folder 'src' search for all files like '.server.ts' and this list:
          - src/lib/app.ts
          - src/lib/index.ts
          - src/lib/stores/**
          - src/lib/utils/**

          All those files must have 80% coverage. DO NOT CHANGE ANYTHING, just add the coverage adding '.spec.ts' files understanding what those files do (if you are not sure, do not try to coverage that)
          Finally, in the README.md you will find what language this project uses as the main language and create the 'summary' in that language.
          Do not create additional files like 'VALIDACAO_COVERAGE.md' or 'SUMMARY_COVERAGE.md' or change the 'README.md'.
          Do not use and verify if exists to rename it files beginning with '+' and ending with '.spec.ts' for example '+app.spec.ts'; DO NOT USE '+' in the name of the file.
          If there are any changes, commit using the summary and push it."
